name: Static Analysis

on: ['push', 'pull_request']

jobs:
  cs:
    runs-on: ubuntu-latest

    name: Code Style

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4
        tools: composer:v2
        coverage: none

    - name: Install Dependencies
      run: composer update --no-interaction --no-progress --ansi

<<<<<<< HEAD
=======
    - name: Run Rector
      run: vendor/bin/rector process src --dry-run --ansi

>>>>>>> a0161d41bddeb4dc8c7102e63cd65a77a9f6f764
    - name: Run PHP-CS-Fixer
      run: vendor/bin/php-cs-fixer fix -v --allow-risky=yes --dry-run --ansi

  phpstan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dependency-version: [prefer-lowest, prefer-stable]

    name: PHPStan ${{ matrix.dependency-version }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4
        tools: composer:v2
        coverage: none

    - name: Install Dependencies
      run: composer update --prefer-stable --no-interaction --no-progress --ansi

    - name: Run PHPStan
      run: vendor/bin/phpstan analyse --no-progress --ansi
